/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * what is an bootloader ?
 * is software or firmware that is used to done init and transfer control to the application program
 * used to program the flash chip using serial device peripherals / update firmware
 * with the bootloader the firmware can be updated over the air , via a wired or wireless connection , or even by end user using simple interface *
 * bootloader can also provide recovery mechanism , load another firmware from another slot incase the primary fails /
 */

/*Modules
 * FPU , is a core peripheral that comes with ARM arch
 * USART , is MCU peripheral
 * GPIO , is MCU peripheral
 * TIMEBASE
 * */

#include <stdint.h>
#include <string.h>
/*GPIO init for button */
/*Usart 2 pin on the MCU is used for serial communication with , PA2 and PA3 pin are connected to ST-Link provides virtual com support */
/* the native ST bootloader stored in system memory (ROM) interacts with user / outside over USARt3 and USARt1*/
/* short the boot pin (boot0 as high by connecting to VDD) , enable the bootloader , than load the firmware -> for this we need USB to UART dongle*/


#include "fpu.h"
#include "usart.h"
#include "timebase.h"
#include "bsp.h"

#define LOW 		0
#define HIGH 		1

char *msg="Testing USART2 transmit, VCOM.\r\n";
volatile uint32_t get_current_tick = 0; // using volatile for ISR shared variable

// note : on reset the 16Mhz internal RC oscillator is selected as default CPU clock
int main()
{

	fpu_enable(); // enbales the floating point unit

	usart2_init(); // enable the usart2

	timebase_init();

	led_init();

	user_button_init();

	while(1)
	{
		// we want a delay of 5 sec
		// use timers for this , we have implemented systick timer to get 1 tick per seconds
		//usart2_transmit(USART2, (uint8_t*)msg, strlen(msg));
		//delay(5);
		if(user_button_read_input_pin(13)==LOW)
		{
			//button is  pressed
			led_on();
		}



	}


	return 0;

}

void SysTick_Handler()
{
	tick_increement();
}
